name: sip_track
description: A fun alcohol tracking app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.1.1
  uuid: ^3.0.7
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.3
  table_calendar: ^3.0.9
  flutter_local_notifications: ^19.2.0
  timezone: ^0.10.1
  flutter_native_timezone: ^2.0.0
  url_launcher: ^6.3.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  share_plus: ^4.0.10

#  awesome_notifications_core: ^0.10.0 # use the latest core version available
#  awesome_notifications: ^0.10.0 # This version is managed by core plugin
#  awesome_notifications_fcm: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true